package ru.protei.portal.ui.common.client.widget.selector.sortfield;

/**
 * Модули
 */
public enum ModuleType {
    COMPANY, PRODUCT, CONTACT, ISSUE, EQUIPMENT, ROLE, OFFICIAL, DOCUMENT, DOCUMENT_TYPE, ACCOUNT, SITE_FOLDER, EMPLOYEE,
    EMPLOYEE_REGISTRATION, CONTRACT, PROJECT, REGION, SUBNET, RESERVED_IP, PLAN, ABSENCE, DUTY_LOG, SITE_FOLDER_SERVER,
    DELIVERY, CARD, CARD_BATCH, PCB_ORDER;
}
