variables:
  PROTEI_PROJECT_CURRENT_PATH: documentation

stages:
  - sync docs
  - build
  - validate
  - test
  - deploy

sync-docs:
  stage: sync docs
  trigger: department-7/documentation
  variables:
    PROTEI_PROJECT_NAME: $CI_PROJECT_NAME
    PROTEI_PROJECT_CLONE: "${CI_PROJECT_PATH}.git"
    PROTEI_PROJECT_BRANCH: $CI_COMMIT_REF_NAME
    PROTEI_PROJECT_PATH: $PROTEI_PROJECT_CURRENT_PATH
    PROTEI_COMMIT_INITIATOR: $GITLAB_USER_EMAIL
    PROTEI_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
  only:
    refs:
      - develop
    changes:
      - documentation/**/*

validate-ts:
  stage: validate
  image: node:16-alpine
  tags:
    - department-7-runner
  before_script:
    - sh ./webts/scripts/install.sh
  script:
    - sh ./webts/scripts/validate.sh ci
  artifacts:
    name: "validate-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/code-quality-report.html
    reports:
      codequality: build/code-quality-report-gitlab.json

test-ts:
  stage: test
  image: node:16-alpine
  tags:
    - department-7-runner
  before_script:
    - sh ./webts/scripts/install.sh
  script:
    - sh ./webts/scripts/test.sh ci
  artifacts:
    name: "test-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/coverage/lcov-report/*
