export enum ExceptionName {
  NATIVE = "NATIVE",
  REACT = "REACT",
  UNAVAILABLE = "UNAVAILABLE",
  ILLEGAL_STATE = "ILLEGAL_STATE",
  ILLEGAL_ARGUMENT = "ILLEGAL_ARGUMENT",
  API = "API",
  API_OFFLINE = "API_OFFLINE",
  API_DISCONNECTED = "API_DISCONNECTED",
  API_TIMEOUT = "API_TIMEOUT",
  API_PARSE = "API_PARSE",
  API_ERROR = "API_ERROR",
  API_AUTH_FAILED = "API_AUTH_FAILED",
}
