INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (1, 'bug', 'Проблема', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (2, 'task', 'Задача', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (3, 'freq', 'Запрос на доработку', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (4, 'crm.sr', 'CRM-обращение в техподдержку', 1019256);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (5, 'crm.mr', 'CRM-маркетинг', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (6, 'sysadm', 'Обращение в службу системных администраторов', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (7, 'plan', 'План', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (8, 'order', 'Заказ', 1000000);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (9, 'project', 'Проект', 1000196);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (10, 'official', 'Должностное лицо', 100);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (11, 'employee-reg', 'Анкета нового сотрудника', 82);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (12, 'contract', 'Договора', 20);
INSERT INTO portal_dev.case_type (ID, CT_CODE, CT_INFO, NEXT_ID) VALUES (13, 'sf-platform', 'Платформы', 0);