INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (1, 'business_trip', 'Командировка', 1, 2);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (2, 'vacation', 'Отпуск', 2, 5);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (3, 'illness', 'Болезнь', 3, 6);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (4, 'personal_reasons', 'Личные дела', 4, 1);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (5, 'local_trip', 'Местная командировка', 5, 3);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (6, 'studies', 'Учеба', 6, 4);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (7, 'sick_leave', 'Больничный лист', 7, 7);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (8, 'guest_card', 'Гостевая карта', 8, 8);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (9, 'night_work', 'Ночные работы', 9, 9);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (10, 'leave_without_pay', 'Отпуск за свой счет', 10, 10);
INSERT INTO portal_dev.absence_reason (id, ar_code, ar_info, old_id, display_order) VALUES (11, 'schedule', 'Расписание', 11, 11);