INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (1, 'head_manager', null);
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (2, 'deploy_manager', null);
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (3, 'decision_center', 'Центр принятия решений');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (4, 'chief_decision_maker', 'Главный ЛПР');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (5, 'decision_keeper', 'Привратник');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (6, 'tech_specialists', 'Технические специалисты');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (7, 'influence_maker', 'Лицо, влияющее на принятие решений');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (8, 'chief_influence_maker', 'Главное лицо, влияющее на принятие решений');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (9, 'economist', 'Экономист');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (10, 'well_wisher', 'Доброжелатель');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (11, 'receptivity_center', 'Центр восприимчивости');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (12, 'hardware_curator', 'АО - Курирование вопросов разработки аппаратного обеспечения');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (13, 'software_curator', 'ПО - Курирование вопросов разработки программного обеспечения');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (14, 'intro_new_tech_solutions', 'В - Внедрение новых технологических решений');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (15, 'liable_for_auto_testing', 'ОТК - Ответственный за автоматизированное тестирование компонентов комплекса');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (16, 'tech_support_curator', 'ТП - Курирует все вопросы технической поддержки комплекса');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (17, 'product_assembler', 'СБ - Сборка изделия из комплектующих изделий');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (18, 'supply_preparation', 'ПП - Подготовка поставки. Производство комплектующих изделий');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (19, 'engineer_doc_dev', 'КД - Разработка конструкторской документации');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (20, 'tech_doc_dev', 'ТД - Разработка технологической документации');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (21, 'software_doc_dev', 'ПД - Разработка программной документации');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (22, 'liable_for_certification', 'С - Сертификационная деятельность');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (23, 'okr_escort', 'ОКР - Сопровождение ОКР');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (24, 'quality_control_smk', 'КК - Контроль качества в рамках СМК, учет движения комплектующих изделий на всех этапах производства');
INSERT INTO portal_dev.dev_unit_mrole (ID, UROLE_CODE, UROLE_INFO) VALUES (25, 'customer_integration', 'РП - Проектная деятельность. Взаимодействие с заказчиком');