INSERT INTO portal_dev.audit_type (id, code, info) VALUES (1, 'ISSUE_MODIFY', 'Изменение обращения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (2, 'ISSUE_CREATE', 'Создание обращения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (3, 'ISSUE_REPORT', 'Создание отчета по обращениям');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (4, 'ISSUE_EXPORT', 'Экспорт обращений');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (5, 'REGION_MODIFY', 'Изменение региона');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (6, 'REGION_REPORT', 'Создание отчета по регионам');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (7, 'REGION_EXPORT', 'Экспорт регионов');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (8, 'PROJECT_MODIFY', 'Изменение проекта');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (9, 'PROJECT_CREATE', 'Создание проекта');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (10, 'COMPANY_MODIFY', 'Изменение компании');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (11, 'COMPANY_CREATE', 'Создание компании');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (12, 'PRODUCT_MODIFY', 'Изменение продукта');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (13, 'PRODUCT_CREATE', 'Создание продукта');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (14, 'CONTACT_MODIFY', 'Изменение контактного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (15, 'CONTACT_CREATE', 'Создание контактного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (16, 'ACCOUNT_MODIFY', 'Изменение учетной записи');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (17, 'ACCOUNT_CREATE', 'Создание учетной записи');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (18, 'ACCOUNT_REMOVE', 'Удаление учетной записи');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (19, 'EQUIPMENT_MODIFY', 'Изменение оборудования');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (20, 'EQUIPMENT_CREATE', 'Создание оборудования');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (21, 'EQUIPMENT_REMOVE', 'Удаление оборудования');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (22, 'ROLE_MODIFY', 'Изменение роли');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (23, 'ROLE_CREATE', 'Создание роли');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (24, 'ISSUE_COMMENT_CREATE', 'Создание описания для обращения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (25, 'ISSUE_COMMENT_MODIFY', 'Изменение описания для обращения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (26, 'ISSUE_COMMENT_REMOVE', 'Удаление описания для обращения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (27, 'ATTACHMENT_REMOVE', 'Удаление вложения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (28, 'EQUIPMENT_COPY', 'Копирование оборудования');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (29, 'OFFICIAL_MODIFY', 'Изменение должностного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (30, 'OFFICIAL_CREATE', 'Создание должностного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (31, 'ROLE_REMOVE', 'Удаление роли');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (32, 'EMPLOYEE_MODIFY', 'Изменение сотрудника');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (33, 'EMPLOYEE_CREATE', 'Создание сотрудника');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (34, 'DEPARTMENT_MODIFY', 'Изменение отдела');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (35, 'DEPARTMENT_CREATE', 'Создание отдела');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (36, 'DEPARTMENT_REMOVE', 'Удаление отдела');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (37, 'WORKER_MODIFY', 'Изменение записи о сотруднике');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (38, 'WORKER_CREATE', 'Создание записи о сотруднике');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (39, 'WORKER_REMOVE', 'Удаление записи о сотруднике');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (40, 'POSITION_MODIFY', 'Изменение должности');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (41, 'POSITION_CREATE', 'Создание должности');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (42, 'POSITION_REMOVE', 'Удаление должности');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (43, 'PHOTO_UPLOAD', 'Загрузка фотографии сотрудника');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (44, 'DOCUMENT_MODITY', 'Изменение документа');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (45, 'DOCUMENT_REMOVE', 'Удаление документа');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (46, 'EMPLOYEE_REGISTRATION_CREATE', 'Создание анкеты нового сотрудника');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (47, 'PROJECT_REMOVE', 'Удаление проекта');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (48, 'EMPLOYEE_REGISTRATION_MODIFY', 'Изменение анкеты нового сотрудника');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (49, 'CONTRACT_MODIFY', 'Изменение договора');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (50, 'CONTRACT_CREATE', 'Создание договора');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (51, 'CONTACT_FIRE', 'Увольнение контактного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (52, 'CONTACT_DELETE', 'Удаление контактного лица');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (53, 'LINK_CREATE', 'Создание ссылки');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (54, 'LINK_REMOVE', 'Удаление ссылки');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (55, 'DOCUMENT_CREATE', 'Создание документа');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (56, 'DOCUMENT_TYPE_CREATE', 'Создание типа документа');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (57, 'DOCUMENT_TYPE_REMOVE', 'Удаление типа документа');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (58, 'PLATFORM_CREATE', 'Создание площадки');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (59, 'PLATFORM_MODIFY', 'Изменение площадки');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (60, 'PLATFORM_REMOVE', 'Удаление площадки');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (61, 'SERVER_CREATE', 'Создание сервера');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (62, 'SERVER_MODIFY', 'Изменение сервера');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (63, 'SERVER_REMOVE', 'Удаление сервера');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (64, 'APPLICATION_CREATE', 'Создание приложения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (65, 'APPLICATION_MODIFY', 'Изменение приложения');
INSERT INTO portal_dev.audit_type (id, code, info) VALUES (66, 'APPLICATION_REMOVE', 'Удаление приложения');