INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (1, 1, 1, 1, 1, 'submitted', 'submitted');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (2, 1, 2, 2, 2, 'opened', 'opened');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (3, 1, 3, 10, 3, 'closed', 'closed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (4, 1, 4, 11, 4, 'paused', 'paused');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (5, 1, 5, 9, 6, 'verified', 'verified');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (6, 1, 6, 8, 8, 'reopened', 'reopened');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (7, 1, 7, 3, 9, 'resolved not a problem', 'solved: not a problem');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (8, 1, 8, 5, 11, 'resolved fixed', 'solved: fixed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (9, 1, 9, 6, 12, 'resolved duplicated', 'solved: duplicated');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (10, 1, 10, 7, 13, 'resolved ignored', 'ignored');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (20, 2, 1, 1, 1, 'submitted', 'submitted');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (21, 2, 11, 2, 2, 'assigned', 'assigned');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (22, 2, 12, 3, 3, 'estimated', 'estimated');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (23, 2, 2, 4, 4, 'opened', 'opened');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (24, 2, 17, 6, 5, 'completed', 'completed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (25, 2, 3, 7, 6, 'closed', 'closed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (26, 2, 10, 8, 7, 'ignored', 'ignored');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (27, 2, 4, 5, 8, 'paused', 'paused');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (30, 3, 1, 1, 1, 'NEW', 'new');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (31, 3, 2, 3, 2, 'OPEN', 'opened');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (32, 3, 17, 5, 3, 'DONE', 'done');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (33, 3, 18, 6, 4, 'TEST', 'test');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (34, 3, 18, 7, 5, 'VERIFIED', 'verified');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (35, 3, 3, 8, 6, 'CLOSED', 'closed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (36, 3, 10, 9, 7, 'IGNORED', 'ignored');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (37, 3, 4, 4, 8, 'PAUSED', 'paused');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (38, 3, 14, 2, 9, 'DISCUSS', 'discuss');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (40, 4, 1, 1, 1, 'NEW', 'new');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (41, 4, 17, 5, 2, 'DONE', 'done');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (42, 4, 2, 2, 3, 'open', 'open');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (43, 4, 5, 7, 4, 'verified', 'verified');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (44, 4, 16, 3, 5, 'IN_PROCESS', 'in process');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (45, 4, 19, 4, 6, 'LOCAL_TEST', 'local test');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (46, 4, 20, 6, 7, 'CUSTOMER_TEST', 'customer test');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (50, 5, 1, 1, 1, 'NEW', 'new');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (51, 5, 17, 5, 2, 'DONE', 'done');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (52, 5, 2, 2, 3, 'open', 'open');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (53, 5, 5, 7, 4, 'verified', 'verified');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (54, 5, 16, 3, 5, 'IN_PROCESS', 'in process');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (55, 5, 19, 4, 6, 'LOCAL_TEST', 'local test');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (56, 5, 20, 6, 7, 'CUSTOMER_TEST', 'customer test');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (60, 6, 1, 1, 1, 'new', 'new');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (61, 6, 17, 3, 2, 'complete', 'complete');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (62, 6, 16, 2, 3, 'in_process', 'in process');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (63, 6, 10, 4, 6, 'ignore', 'ignored');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (64, 6, 5, 5, 4, 'verified', 'verified');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (70, 7, 15, 1, 1, 'planned', 'planned');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (71, 7, 16, 2, 2, 'active', 'active');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (72, 7, 4, 3, 3, 'paused', 'paused');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (73, 7, 17, 4, 4, 'done', 'done');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (74, 7, 3, 5, 5, 'closed', 'closed');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (75, 9, 22, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (76, 9, 23, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (77, 9, 24, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (78, 9, 25, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (79, 9, 26, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (80, 9, 27, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (81, 9, 28, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (82, 9, 29, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (83, 4, 30, 4, null, null, 'workaround solution');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (84, 4, 31, 4, null, null, 'request information');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (85, 9, 32, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (86, 9, 33, null, null, null, null);
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (87, 4, 34, 4, null, null, 'customer pending');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (88, 4, 33, 7, null, null, 'canceled');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (91, 4, 35, 4, null, null, 'request to NX');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (92, 4, 36, 4, null, null, 'request to customer');
INSERT INTO portal_dev.case_state_matrix (ID, CASE_TYPE, CASE_STATE, view_order, OLD_ID, OLD_CODE, info) VALUES (93, 4, 4, 3, null, null, 'paused');