INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (1, 'created', 'Исходное состояние задачи при её создании.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (2, 'opened', 'Задача открыта и находится в работе. Обязательно должен быть назначен менеджер задачи.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (3, 'closed', 'closed', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (4, 'paused', 'Актуально только дла задач синхронизированных с Jira. Работа над тикетом приостановлена.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (5, 'verified', 'Терминальное состояние задачи. Закрытие задачи проверено (подтверждено) Заказчиком. Переход в другие статусы не возможен.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (6, 'reopened', 'reopened', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (7, 'solved.noap', 'solved: not a problem', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (8, 'solved.fix', 'solved: fixed', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (9, 'solved.dup', 'solved: duplicated', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (10, 'ignored', 'ignored', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (11, 'assigned', 'assigned', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (12, 'estimated', 'estimated', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (14, 'discuss', 'discuss', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (15, 'planned', 'planned', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (16, 'active', 'Задача находится в работе.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (17, 'done', 'Работа по кейсу завершена, ожидается подтверждение Заказчика (статус verified).', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (18, 'test', 'test', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (19, 'test-local', 'Проводится локальное тестирование.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (20, 'test-cust', 'Заказчик осуществляет проверку/тестирование предоставленного решения по кейсу.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (21, 'design', 'design', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (22, 'unknown', 'unknown', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (23, 'marketing', 'marketing', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (24, 'presale', 'presale', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (25, 'projecting', 'projecting', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (26, 'development', 'development', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (27, 'deployment', 'deployment', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (28, 'testing', 'testing', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (29, 'support', 'support', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (30, 'workaround', 'Предоставлено временное решение по кейсу.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (31, 'info.request', 'Запрошена информация у Заказчика необходимая для дальнейшей работы по кейсу.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (32, 'finished', 'finished', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (33, 'canceled', 'Задача потеряла актуальность и была отменена.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (34, 'cust.pending', 'Ожидание Заказчика. Например: ожидание продления договора ПСГО, ожидание предоставления доступа к сервера, ожидание согласования коммерческого заказа, ожидание закупки комплектующих для серверов и т.п.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (35, 'nx.request', 'Актуально только дла задач синхронизированных с Jira. Запрошена информация у Nexign, ожидание ответа.', 1);
INSERT INTO portal_dev.case_state (ID, STATE, INFO, usage_in_companies) VALUES (36, 'customer.request', 'Актуально только дла задач синхронизированных с Jira. Запрошена информация у конечного Заказчика, ожидание ответа.', 1);