export enum SpecificationXLSXColumnType {
  article = "article",
  name = "name",
  configuration = "configuration",
  color = "color",
  modificationN = "modificationN",
  attn = "attn",
  responsible = "responsible",
  supplier = "supplier",
  simplified = "simplified",
  category = "category",
  reserve = "reserve",
  dateModified = "dateModified",
  note = "note",
  specificationId = "specificationId",
  componentType = "componentType",
  partReference = "partReference",
  value = "value",
}
