package ru.protei.portal.core.model.dict;

import ru.protei.winter.core.utils.enums.HasId;

/**
 * Тип операции в системе
 */
public enum En_AuditType implements HasId {
    ISSUE_MODIFY( 1 ),
    ISSUE_CREATE( 2 ),
    ISSUE_REPORT( 3 ),
    ISSUE_EXPORT( 4 ),

    REGION_MODIFY( 5 ),
    REGION_REPORT( 6 ),
    REGION_EXPORT( 7 ),

    PROJECT_MODIFY( 8 ),
    PROJECT_CREATE( 9 ),

    COMPANY_MODIFY( 10 ),
    COMPANY_CREATE( 11 ),

    PRODUCT_MODIFY( 12 ),
    PRODUCT_CREATE( 13 ),

    CONTACT_MODIFY( 14 ),
    CONTACT_CREATE( 15 ),

    ACCOUNT_MODIFY( 16 ),
    ACCOUNT_CREATE( 17 ),
    ACCOUNT_REMOVE( 18 ),

    EQUIPMENT_MODIFY( 19 ),
    EQUIPMENT_CREATE( 20 ),
    EQUIPMENT_REMOVE( 21 ),

    ROLE_MODIFY( 22 ),
    ROLE_CREATE( 23 ),

    ISSUE_COMMENT_CREATE( 24 ),
    ISSUE_COMMENT_MODIFY( 25 ),
    ISSUE_COMMENT_REMOVE( 26 ),

    ATTACHMENT_REMOVE( 27 ),

    EQUIPMENT_COPY( 28 ),

    OFFICIAL_MODIFY( 29 ),
    OFFICIAL_CREATE( 30),

    ROLE_REMOVE( 31 ),

    EMPLOYEE_MODIFY( 32 ),
    EMPLOYEE_CREATE( 33 ),

    DEPARTMENT_MODIFY( 34 ),
    DEPARTMENT_CREATE( 35 ),
    DEPARTMENT_REMOVE( 36 ),

    WORKER_MODIFY( 37 ),
    WORKER_CREATE( 38 ),
    WORKER_REMOVE( 39 ),

    POSITION_MODIFY( 40 ),
    POSITION_CREATE( 41 ),
    POSITION_REMOVE( 42 ),

    PHOTO_UPLOAD( 43 ),

    DOCUMENT_MODIFY(44),
    DOCUMENT_REMOVE(45),

    EMPLOYEE_REGISTRATION_CREATE(46),

    PROJECT_REMOVE(47),

    EMPLOYEE_REGISTRATION_MODIFY(48),

    CONTRACT_MODIFY(49),
    CONTRACT_CREATE(50),

    CONTACT_FIRE(51),
    CONTACT_DELETE(52),

    LINK_CREATE(53),
    LINK_REMOVE(54),

    DOCUMENT_CREATE(55),

    DOCUMENT_TYPE_CREATE(56),
    DOCUMENT_TYPE_REMOVE(57),

    PLATFORM_CREATE(58),
    PLATFORM_MODIFY(59),
    PLATFORM_REMOVE(60),

    SERVER_CREATE(61),
    SERVER_MODIFY(62),
    SERVER_REMOVE(63),

    APPLICATION_CREATE(64),
    APPLICATION_MODIFY(65),
    APPLICATION_REMOVE(66),

    SUBNET_MODIFY(67),
    SUBNET_CREATE(68),
    SUBNET_REMOVE(69),
    RESERVED_IP_MODIFY(70),
    RESERVED_IP_CREATE(71),
    RESERVED_IP_REMOVE(72),

    ROOM_RESERVATION_CREATE(73),
    ROOM_RESERVATION_MODIFY(74),
    ROOM_RESERVATION_REMOVE(75),

    PLAN_CREATE(76),
    PLAN_MODIFY(77),
    PLAN_REMOVE(78),

    ABSENCE_CREATE(79),
    ABSENCE_MODIFY(80),
    ABSENCE_REMOVE(81),

    SUBSCRIPTION_MODIFY(82),

    DUTY_LOG_CREATE(84),
    DUTY_LOG_MODIFY(85),

    SERVER_GROUP_CREATE(86),
    SERVER_GROUP_MODIFY(87),
    SERVER_GROUP_REMOVE(88),

    DELIVERY_CREATE(89),
    DELIVERY_MODIFY(90),
    DELIVERY_REMOVE(91),

    KIT_CREATE(92),
    KIT_MODIFY(93),
    KIT_REMOVE(94),

    MODULE_CREATE(95),
    MODULE_MODIFY(96),
    MODULE_REMOVE(97),
    ;

    En_AuditType(int id ) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    private final int id;
}
