package ru.protei.portal.core.model.dict;

import static ru.protei.portal.core.model.dict.En_PrivilegeAction.*;
import static ru.protei.portal.core.model.dict.En_PrivilegeEntity.*;

/**
 * Привилегии в системе
 */
public enum En_Privilege {
    COMMON_PROFILE_VIEW (PROFILE, VIEW),
    COMMON_PROFILE_EDIT (PROFILE, EDIT),

    ISSUE_VIEW (ISSUE, VIEW),
    ISSUE_EDIT (ISSUE, EDIT),
    ISSUE_CREATE (ISSUE, CREATE),
    ISSUE_REPORT (ISSUE, REPORT),
    ISSUE_EXPORT (ISSUE, EXPORT),

    ISSUE_ASSIGNMENT_VIEW (ISSUE_ASSIGNMENT, VIEW),

    REGION_VIEW (REGION, VIEW),
    REGION_EDIT (REGION, EDIT),
    REGION_REPORT (REGION, REPORT),
    REGION_EXPORT (REGION, EXPORT),

    PROJECT_VIEW (PROJECT, VIEW),
    PROJECT_EDIT (PROJECT, EDIT),
    PROJECT_CREATE (PROJECT, CREATE),
    PROJECT_REMOVE (PROJECT, REMOVE),

    COMPANY_VIEW (COMPANY, VIEW),
    COMPANY_EDIT (COMPANY, EDIT),
    COMPANY_CREATE (COMPANY, CREATE),

    PRODUCT_VIEW (PRODUCT, VIEW),
    PRODUCT_EDIT (PRODUCT, EDIT),
    PRODUCT_CREATE (PRODUCT, CREATE),

    CONTACT_VIEW (CONTACT, VIEW),
    CONTACT_EDIT (CONTACT, EDIT),
    CONTACT_CREATE (CONTACT, CREATE),
    CONTACT_REMOVE (CONTACT, REMOVE),

    ACCOUNT_VIEW (ACCOUNT, VIEW),
    ACCOUNT_EDIT (ACCOUNT, EDIT),
    ACCOUNT_CREATE (ACCOUNT, CREATE),
    ACCOUNT_REMOVE (ACCOUNT, REMOVE),

    EQUIPMENT_VIEW (EQUIPMENT, VIEW),
    EQUIPMENT_EDIT (EQUIPMENT, EDIT),
    EQUIPMENT_CREATE (EQUIPMENT, CREATE),
    EQUIPMENT_REMOVE (EQUIPMENT, REMOVE),

    ROLE_VIEW (ROLE, VIEW),
    ROLE_EDIT (ROLE, EDIT),
    ROLE_CREATE (ROLE, CREATE),
    ROLE_REMOVE (ROLE, REMOVE),

    OFFICIAL_VIEW(OFFICIAL, VIEW),
    OFFICIAL_EDIT(OFFICIAL, EDIT),

    DASHBOARD_VIEW(DASHBOARD, VIEW),

    DOCUMENT_VIEW(DOCUMENT, VIEW),
    DOCUMENT_EDIT(DOCUMENT, EDIT),
    DOCUMENT_CREATE(DOCUMENT, CREATE),
    DOCUMENT_REMOVE(DOCUMENT, REMOVE),

    DOCUMENT_TYPE_VIEW(DOCUMENT_TYPE, VIEW),
    DOCUMENT_TYPE_EDIT(DOCUMENT_TYPE, EDIT),
    DOCUMENT_TYPE_CREATE(DOCUMENT_TYPE, CREATE),
    DOCUMENT_TYPE_REMOVE(DOCUMENT_TYPE, REMOVE),

    CASE_STATES_VIEW (CASE_STATES, VIEW),
    CASE_STATES_EDIT (CASE_STATES, EDIT),
    CASE_STATES_CREATE (CASE_STATES, CREATE),
    CASE_STATES_REMOVE (CASE_STATES, REMOVE),

    SITE_FOLDER_VIEW (SITE_FOLDER, VIEW),
    SITE_FOLDER_EDIT (SITE_FOLDER, EDIT),
    SITE_FOLDER_CREATE (SITE_FOLDER, CREATE),
    SITE_FOLDER_REMOVE (SITE_FOLDER, REMOVE),

    EMPLOYEE_VIEW (EMPLOYEE, VIEW),
    EMPLOYEE_CREATE (EMPLOYEE, CREATE),
    EMPLOYEE_EDIT (EMPLOYEE, EDIT),

    EMPLOYEE_REGISTRATION_VIEW(EMPLOYEE_REGISTRATION, VIEW),
    EMPLOYEE_REGISTRATION_CREATE(EMPLOYEE_REGISTRATION, CREATE),
    EMPLOYEE_REGISTRATION_EDIT(EMPLOYEE_REGISTRATION, EDIT),

    CONTRACT_VIEW (CONTRACT, VIEW),
    CONTRACT_EDIT (CONTRACT, EDIT),
    CONTRACT_CREATE (CONTRACT, CREATE),
    CONTRACT_REPORT (CONTRACT, REPORT),

    EDUCATION_VIEW (EDUCATION, VIEW),
    EDUCATION_CREATE (EDUCATION, CREATE),

    RESERVED_IP_VIEW (RESERVED_IP, VIEW),
    RESERVED_IP_EDIT (RESERVED_IP, EDIT),
    RESERVED_IP_CREATE (RESERVED_IP, CREATE),
    RESERVED_IP_REMOVE (RESERVED_IP, REMOVE),
    SUBNET_VIEW (SUBNET, VIEW),
    SUBNET_EDIT (SUBNET, EDIT),
    SUBNET_CREATE (SUBNET, CREATE),
    SUBNET_REMOVE (SUBNET, REMOVE),

    ROOM_RESERVATION_VIEW (ROOM_RESERVATION, VIEW),
    ROOM_RESERVATION_EDIT (ROOM_RESERVATION, EDIT),
    ROOM_RESERVATION_CREATE (ROOM_RESERVATION, CREATE),
    ROOM_RESERVATION_REMOVE (ROOM_RESERVATION, REMOVE),

    PLAN_VIEW (PLAN, VIEW),
    PLAN_EDIT (PLAN, EDIT),
    PLAN_CREATE (PLAN, CREATE),
    PLAN_REMOVE (PLAN, REMOVE),

    ABSENCE_VIEW(ABSENCE, VIEW),
    ABSENCE_CREATE(ABSENCE, CREATE),
    ABSENCE_EDIT(ABSENCE, EDIT),
    ABSENCE_REMOVE(ABSENCE, REMOVE),
    ABSENCE_REPORT(ABSENCE, REPORT),

    DUTY_LOG_VIEW(DUTY_LOG, VIEW),
    DUTY_LOG_CREATE(DUTY_LOG, CREATE),
    DUTY_LOG_EDIT(DUTY_LOG, EDIT),
    DUTY_LOG_REPORT(DUTY_LOG, REPORT),

    DELIVERY_VIEW(DELIVERY, VIEW),
    DELIVERY_CREATE(DELIVERY, CREATE),
    DELIVERY_EDIT(DELIVERY, EDIT),
    DELIVERY_REMOVE(DELIVERY, REMOVE),
    DELIVERY_CHANGE_PRELIMINARY_STATUS(DELIVERY, EDIT),

    YT_REPORT (YT, REPORT),

    CARD_VIEW(CARD, VIEW),
    CARD_CREATE(CARD, CREATE),
    CARD_EDIT(CARD, EDIT),
    CARD_REMOVE(CARD, REMOVE),

    CARD_BATCH_VIEW(CARD_BATCH, VIEW),
    CARD_BATCH_CREATE(CARD_BATCH, CREATE),
    CARD_BATCH_EDIT(CARD_BATCH, EDIT),
    CARD_BATCH_REMOVE(CARD_BATCH, REMOVE),

    // Набор дополнительных привилегий, которые вычисляются по scope и не пишутся в базу. Устанавливаются без action
    ISSUE_COMPANY_EDIT(ISSUE, null),
    ISSUE_PLAN_EDIT (ISSUE, null),
    ISSUE_PRODUCT_EDIT(ISSUE, null),
    ISSUE_MANAGER_EDIT(ISSUE, null),
    ISSUE_PLATFORM_EDIT(ISSUE, null),
    ISSUE_PRIVACY_VIEW(ISSUE, null),
    ISSUE_WORK_TIME_VIEW(ISSUE, null),
    ISSUE_PLATFORM_VIEW(ISSUE, null),

    ISSUE_FILTER_COMPANY_VIEW(ISSUE, null),
    ISSUE_FILTER_MANAGER_VIEW(ISSUE, null),
    ISSUE_FILTER_PRODUCT_VIEW(ISSUE, null),
    ISSUE_FILTER_PLAN_VIEW(ISSUE, null),

    @Deprecated
    DASHBOARD_ALL_COMPANIES_VIEW(DASHBOARD, VIEW);

    private final En_PrivilegeEntity entity;
    private final En_PrivilegeAction action;

    public final static En_Privilege [] CLIENT_SYSTEM_SCOPE_PRIVILEGES = {
            ISSUE_COMPANY_EDIT,
            ISSUE_PRODUCT_EDIT,
            ISSUE_MANAGER_EDIT,
            ISSUE_PLATFORM_EDIT,
            ISSUE_PRIVACY_VIEW,
            ISSUE_WORK_TIME_VIEW,
            ISSUE_PLATFORM_VIEW,
            ISSUE_PLAN_EDIT,

            ISSUE_FILTER_COMPANY_VIEW,
            ISSUE_FILTER_MANAGER_VIEW,
            ISSUE_FILTER_PRODUCT_VIEW,
            ISSUE_FILTER_PLAN_VIEW
    };

    En_Privilege( En_PrivilegeEntity entity, En_PrivilegeAction action ) {
        this.entity = entity;
        this.action = action;
    }

    public En_PrivilegeEntity getEntity() {
        return entity;
    }

    public En_PrivilegeAction getAction() {
        return action;
    }

    public String getActionShortName() {
        return action == null ? "" : action.getShortName();
    }

    public Integer getOrder() {
        return entity.getOrder() + (action == null ? 0 : action.getOrder());
    }

    public static En_Privilege findPrivilege( En_PrivilegeEntity entity, En_PrivilegeAction action ) {
        for ( En_Privilege privilege : values() ) {
            if ( privilege.action == null ) {
                continue;
            }

            if ( privilege.action.equals( action ) && privilege.entity.equals( entity ) ) {
                return privilege;
            }
        }

        return null;
    }
}
